version: "3.8"

services:
  airflow-postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data


  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    ports:
      - "5000:5000"
    # Guardamos la DB dentro de la carpeta mlruns para evitar errores en Windows
    command: mlflow server --backend-store-uri sqlite:///mlruns/mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0
    volumes:
      - ./mlruns:/mlruns

  airflow-init:
    build: .
    depends_on:
      - airflow-postgres
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
    entrypoint: ["airflow", "db", "init"]

  airflow-webserver:
    build: .
    depends_on:
      - airflow-init
      - airflow-postgres
      - mlflow
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - DATA_DIR=/opt/airflow/data
    ports:
      - "8080:8080"
    command: ["airflow", "webserver"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data

  airflow-scheduler:
    build: .
    depends_on:
      - airflow-webserver
      - airflow-postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - DATA_DIR=/opt/airflow/data
    command: ["airflow", "scheduler"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data

volumes:
  postgres_data: